services:
  - type: web
    name: budget-tracker
    env: python
    buildCommand: |
      # Install Node.js and npm
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      # Install dependencies and build
      pip install -r requirements.txt
      npm install
      npm run build:css
      mkdir -p flask_session
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
    staticPublishPath: ./static
    staticHeaders:
      - path: /static/*
        headers:
          - key: Cache-Control
            value: public, max-age=31536000
