services:
  - type: web
    name: budget-tracker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p flask_session
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    staticPublishPath: ./static
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/*
