services:
  - type: web
    name: budget-tracker
    env: python
    buildCommand: |
      # Install Node.js and npm
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      
      # Install dependencies
      pip install -r requirements.txt
      npm install
      
      # Build Tailwind CSS
      echo "Building Tailwind CSS..."
      npx tailwindcss -i ./static/css/main.css -o ./static/css/dist/main.css --minify
      
      # Move static files to root level
      mkdir -p public/css/dist
      cp static/css/dist/main.css public/css/dist/
      
      # Debug: Show file contents
      echo "Listing public directory contents:"
      ls -R public/
      
      # Create session directory
      mkdir -p flask_session
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: SITE_URL
        value: https://budgettracker.pro
      - key: FLASK_DEBUG
        value: "True"
    staticPublishPath: ./public
    staticHeaders:
      - path: /*
        headers:
          - key: Cache-Control
            value: public, max-age=31536000
